version: '3'

networks:
  backend:
    driver: bridge

services:
  db:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: std_1111_exam
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./data:/var/lib/mysql
      - ./startup_scripts:/docker-entrypoint-initdb.d
    networks:
      - backend
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8091:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - backend
  back:
    build: ./
    volumes:
      - ./:/code
    ports:
      - "8006:8006"
    networks:
      - backend